# Site wide configuration
locale: en_US
title: Random Notes on Automation and PowerShell
title_separator: "-"
name: Jon Mattivi
description: >- # this means to ignore newlines until "baseurl:"
  Automation and PowerShell
url: http://jmattivi.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-remote-theme

#Site Author
author:
  name: Jon Mattivi
  avatar: /assets/images/bio.jpg
  bio: "Systems Engineer working in the healthcare industry."
  location: Danville, PA
  github: jmattivi
  linkedin: jonmattivi
  google_plus: 104511119455541238503
  twitter: jonmattivi

#Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-32504876-2"

#Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

#Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      header:
        image: /assets/images/banner2.png
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: true
      header:
        image: /assets/images/banner2.png
      
